huh:
  encore:
    entries:
      - { name: contao-tiny-slider-bundle, file: "vendor/heimrichhannot/contao-tiny-slider-bundle/src/Resources/assets/js/contao-tiny-slider-bundle.js", requiresCss: true }
      - { name: contao-tiny-slider-bundle-theme, file: "vendor/heimrichhannot/contao-tiny-slider-bundle/src/Resources/assets/js/contao-tiny-slider-bundle-theme.js", requiresCss: true }
    legacy:
      js:
        - tiny-slider
        - contao-tiny-slider-bundle
      css:
        - tiny-slider
        - contao-tiny-slider-bundle