services:
  _defaults:
    public: false
    autowire: true

  HeimrichHannot\TinySliderBundle\EventListener\LoadDataContainerListener:
    public: true

  HeimrichHannot\TinySliderBundle\EventListener\ListBeforeRenderListener:
    tags:
      - { name: kernel.event_listener, event: huh.list.event.list_before_render, method: onListBeforeRender }