services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - ["setContainer", ["@service_container"]]

  HeimrichHannot\TinySliderBundle\:
    resource: '../../{DataContainer,EventListener}/*'
    autoconfigure: true
    autowire: true
    public: true

  HeimrichHannot\TinySliderBundle\Util\Config:
    public: true

  huh.tiny_slider.util.config:
    class: HeimrichHannot\TinySliderBundle\Util\Config
    public: true

  huh.tiny_slider.util.dca:
    class: HeimrichHannot\TinySliderBundle\Util\Dca
    public: true
  huh.tiny_slider.backend.tiny_slider_spread:
    class: HeimrichHannot\TinySliderBundle\Backend\TinySliderSpread
    public: true
  huh.twig.extension.tiny_slider:
    class: HeimrichHannot\TinySliderBundle\Twig\TinySliderExtension
    tags: [twig.extension]

  HeimrichHannot\TinySliderBundle\ConfigElementType\TinySliderConfigElementType:
    public: false
    autowire: true
    tags: ['huh.reader.config_element_type', 'huh.list.config_element_type']

  HeimrichHannot\TinySliderBundle\Asset\FrontendAssets:
    public: true
    autowire: true

  HeimrichHannot\TinySliderBundle\Asset\EncoreExtension:
    autoconfigure: true
